// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vp5EvKyQ6s5GCarkDkRDd27C6hDP6pM',
    appId: '1:507381784014:android:603a9eb5bcdfb5e2025f9f',
    messagingSenderId: '507381784014',
    projectId: 'threadapp-d3da2',
    databaseURL: 'https://threadapp-d3da2-default-rtdb.firebaseio.com',
    storageBucket: 'threadapp-d3da2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABQhGe3tybj2MMZS6YhYpNEoV_zagHT2A',
    appId: '1:507381784014:ios:aa0c4038a676574d025f9f',
    messagingSenderId: '507381784014',
    projectId: 'threadapp-d3da2',
    databaseURL: 'https://threadapp-d3da2-default-rtdb.firebaseio.com',
    storageBucket: 'threadapp-d3da2.appspot.com',
    iosBundleId: 'com.mo7.todoRiverpod',
  );
}
